= {name-sdk} Quickstart Guide
:page-toclevels: 2
:description: Install, connect, try. A quick start guide to get you up and running with Enterprise Analytics and the {name-sdk}.

[abstract]
{description}

include::analytics-sdk:shared:partial$start-using-sdk.adoc[tag=intro]


== Before You Start


////
[tabs]
==== 
Capella Analytics::
+
--
Sign up for a xref:cloud:get-started:create-account.adoc[Capella account],
and choose a xref:columnar:intro:intro.adoc[Analytics] cluster.

After creating the cluster, add your IP address to the list of allowed IP addresses.
// TODO: Link to https://docs.couchbase.com/columnar/admin/ip-allowed-list.html
--

Self-Managed Enterprise Analytics::
+
--
*TODO* links to EA docs
--
====
////

Install and configure an xref:enterprise-analytics:intro:intro.adoc[Enterprise Analytics Cluster].


=== Minimum Go Version

In line with the Golang project, the {name-sdk} supports both the current, and the previous, versions of Go.
Earlier versions may work, but are not supported.


== Adding the SDK to an Existing Project

Declare a dependency on the SDK using its xref:project-docs:sdk-full-installation.adoc[].

To see log messages from the SDK, xref:howtos:logging.adoc[consult the logging documentation].


== Connecting and Executing a Query


The 1.1 {name-sdk} adds support for JWT and client certificate authentication, as well as a new "async" poll-based API that uses request handles to fetch results.
Introduced in the 2.2 release of self-managed Enterprise Analytics Server, this API eliminates the need for long-running server connections.

The examples in this first section of the page are for the standard API -- async on the client side -- working with all 2.x releases of Enterprise Analytics (with Server Async examples following in the <<#server-asynchronous-api,Server Async section>>).
Note, you will still be able to use this API with 2.2+ releases of Enterprise Analytics, in addition to the new API.

=== Server Synchronous API

[source,go]
----
include::devguide:example$helloworld.go[tags=**]
----



=== Server Asynchronous API

In the 2.2 release, the Enterprise Analytics Server introduces an asynchronous request API.
The SDK sends a request, polls for results, and then fetches once the result is available.
The SDK supports each stage of this information flow:

`cluster.StartQuery()` → `QueryHandle` → `QueryStatus` → `resultsHandle`

.Server Asynchronous API Example
[source,go]
----
include::devguide:example$serverasync.go[indent=0,tag=server-async]
----


=== Connection String

The `connStr` in the above example should take the form of "https://<your_hostname>:" + PORT 

include::{version-common}@analytics-sdk:shared:partial$connstr.adoc[tag=connstr]

[source,go]
----
const (
		connStr  = "https://analytics.example.com:18095"
		username = "user"
		password = "password"
	)
----




== Migration from Row-Based Analytics

include::{version-common}@analytics-sdk:shared:partial$migration.adoc[tag=migration]
